### ISSUE TITLE
Action you are trying to perform is forbidden by Bitbucket

### ISSUE THREAD

**Issue by iamtodor** [palyuga/BitbucketHelper4Idea#67]
Hello guys, thank you for the plugin. After I dealt with the documentation I got the following error, as the topic name states: `Action you are trying to perform is forbidden by Bitbucket`
How to handle this response? What should I do or fix something?

**Comment by palyuga** [comment]
Hi @iamtodor 
Do you have something related in the IDE's log?
You can access it in Help -> Show Log in Explorer

**Comment by iamtodor** [comment]
@palyuga I think I found it:
```
2019-07-20 17:35:08,188 [368012225]  ERROR -              #UpdateTaskHolder - PyCharm 2019.1.3  Build #PY-191.7479.30 
2019-07-20 17:35:08,188 [368012225]  ERROR -              #UpdateTaskHolder - JDK: 11.0.2; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-07-20 17:35:08,188 [368012225]  ERROR -              #UpdateTaskHolder - OS: Mac OS X 
2019-07-20 17:35:08,188 [368012225]  ERROR -              #UpdateTaskHolder - Plugin to blame: myBitbucket version: 0.2 
2019-07-20 17:35:08,189 [368012226]  ERROR -              #UpdateTaskHolder - Last Action: ShowLog 
2019-07-20 17:35:23,824 [368027861]  ERROR -              #UpdateTaskHolder - Request failed 
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Too': was expecting ('true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@63ca212e; line: 1, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3451)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2610)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:841)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:737)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:378)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1494)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)
	at http.HttpResponseHandler$handle$1.invoke(HttpResponseHandler.kt:17)
	at http.HttpResponseHandler$handle$1.invoke(HttpResponseHandler.kt:11)
	at http.HttpResponseHandler$Companion.process(HttpResponseHandler.kt:40)
	at http.HttpResponseHandler$Companion.access$process(HttpResponseHandler.kt:19)
	at http.HttpResponseHandler.handle(HttpResponseHandler.kt:17)
	at bitbucket.BitbucketClient.sendRequest(BitbucketClient.kt:135)
	at bitbucket.BitbucketClient.replayPageRequest(BitbucketClient.kt:139)
	at bitbucket.BitbucketClient.inbox(BitbucketClient.kt:85)
	at bitbucket.BitbucketClient.inbox$default(BitbucketClient.kt:79)
	at bitbucket.BitbucketClient.reviewedPRs(BitbucketClient.kt:40)
	at UpdateTaskHolder$UpdateTask.run(UpdateTaskHolder.kt:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:226)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by iamtodor** [comment]
@palyuga ping

**Comment by iamtodor** [comment]
@palyuga ping
