### ISSUE TITLE
Listing PRs fails due to limited HTTP-Connections

### ISSUE THREAD

**Issue by cloudyster** [palyuga/BitbucketHelper4Idea#74]
Hi,

I got the following exception when the plugin is trying to examine the pull-requests:

```
2020-06-18 12:50:39,062 [ 586617]  ERROR -              #UpdateTaskHolder - IntelliJ IDEA 2020.1.2  Build #IU-201.7846.76
2020-06-18 12:50:39,062 [ 586617]  ERROR -              #UpdateTaskHolder - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2020-06-18 12:50:39,062 [ 586617]  ERROR -              #UpdateTaskHolder - OS: Linux
2020-06-18 12:50:39,062 [ 586617]  ERROR -              #UpdateTaskHolder - Plugin to blame: myBitbucket version: 0.4
2020-06-18 12:50:39,062 [ 586617]  ERROR -              #UpdateTaskHolder - Last Action: ShowSettings
2020-06-18 12:52:02,402 [ 669957]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2020-06-18 12:52:02,473 [ 670028]   INFO - ateSettings.impl.UpdateChecker - failed to load plugin descriptions from : Malformed URL:
2020-06-18 12:52:15,955 [ 683510]  ERROR -              #UpdateTaskHolder - Request failed
org.apache.http.impl.execchain.RequestAbortedException: Request aborted
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:193)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
    at bitbucket.BitbucketClient.sendRequest(BitbucketClient.kt:135)
    at bitbucket.BitbucketClient.replayPageRequest(BitbucketClient.kt:139)
    at bitbucket.BitbucketClient.inbox(BitbucketClient.kt:85)
    at bitbucket.BitbucketClient.inbox$default(BitbucketClient.kt:79)
    at bitbucket.BitbucketClient.ownPRs(BitbucketClient.kt:44)
    at UpdateTaskHolder$UpdateTask.run(UpdateTaskHolder.kt:61)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
    at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:393)
    at org.apache.http.pool.AbstractConnPool.access$300(AbstractConnPool.java:70)
    at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:253)
    at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:198)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:306)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
    ... 19 more
```

This is probaply caused by the default max-size for the httpconnection-pool (5) and a large number of PRs (>100) in my repo.

As a workaround I've set system property http.maxConnections to 100 (for apache htpclient) in IDEA.

Yours,
Marc

**Comment by palyuga** [comment]
@cloudyster probably it was caused by the status requests that used to be performed for every pull request.
Now the amount of requests is significantly reduced: the plugin supports versioning for PRs so it re-requests status only if PR's version is changed
